### ISSUE TITLE
The running time

### ISSUE THREAD

**Issue by ZXin0305** [zju3dv/SMAP#50]
hi,I want to ask that you how to calculate the running time of the model.It's seems  that if I calculate all the time includes all net parts and some post-porcess parts,the average time is about 100 ms that is different to the value  in paper.But i think it's enough fast in real scene.Thanks a lot!!

**Comment by raypine** [comment]
What device do you use ?

**Comment by ZXin0305** [comment]
> What device do you use ?

thanks for your reply.The device i use is a single Titan xp.

**Comment by raypine** [comment]
We use 1080Ti GPU and Intel Core i7-7820X CPU @ 3.60GHz x 8, but it seems not the reason.
One thing I would like to declare is that in order to compare ours with the baseline method (Moon et al., a multi-stage method), we calculate the running time for the network, DAPA and the refinement separately, not including the immediate data transfer, as we reported in the table. Maybe it's the reason ?

**Comment by ZXin0305** [comment]
> We use 1080Ti GPU and Intel Core i7-7820X CPU @ 3.60GHz x 8, but it seems not the reason. One thing I would like to declare is that in order to compare ours with the baseline method (Moon et al., a multi-stage method), we calculate the running time for the network, DAPA and the refinement separately, not including the immediate data transfer, as we reported in the table. Maybe it's the reason ?

Yes.i think it's the reason.I  also add the immediate data transfer time-comsuming.Thanks for your reply and great work.
